### ISSUE TITLE
shorten drush site:install snippet

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa_profile#2]
The snippet in the readme is nice but I'm wondering if we could shorten it? I run it a lot locally. :)

I think its safe to make some assumptions about some of those values.

**Comment by genjohnson** [comment]
Oh yeah :) Turns out `--locale` defaults to "en", so we can remove that.

I'm not sure about some of the others (like timezone and checking for updates), but I'll be installing a couple more sites locally and will play around with this. I think we could always set default values for these things in the install profile, too.

**Comment by richardbporter** [comment]
Whoops, thats what I meant: make those default values in the profile.

**Comment by genjohnson** [comment]
Ah, gottcha! I agree it'd be nice to set those values in the profile.

**Comment by genjohnson** [comment]
Got a bit ahead of myself with opening a PR vs just creating a branch, but we can work on this in #6 (branch `2-shorten_si_snipped`) and I've started by removing `--locale`.
